// Generated by CoffeeScript 1.4.0

module.exports = Em.View.extend({
  tagName: "li",
  classNameBindings: ["active"],
  template: Em.Handlebars.compile("<a href=\"javascript:\">{{view.content}}</a>"),
  active: (function() {
    if (this.get("parentView.selected") === this.get("content")) {
      return true;
    }
  }).property("parentView.selected"),
  click: function() {
    return this.set("parentView.selected", this.get("content"));
  }
});
