// Generated by CoffeeScript 1.4.0
var get, set,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

get = Em.get;

set = Em.set;

module.exports = Em.Mixin.create({
  tagName: 'li',
  classNameBindings: ['active'],
  template: Em.Handlebars.compile(require('./template')),
  active: (function() {
    var checked, content, selected;
    content = get(this, 'content');
    selected = get(this, 'parentView.selected');
    checked = get(this, 'parentView.checked');
    if (content === selected) {
      return true;
    } else if (checked != null ? checked.contains(content) : void 0) {
      return true;
    }
  }).property('parentView.selected', 'parentView.checked.length'),
  click: function() {
    var checked, content, selected;
    content = get(this, 'content');
    selected = get(this, 'parentView.selected');
    checked = get(this, 'parentView.checked');
    set(this, 'parentView.selected', content);
    if (__indexOf.call(checked != null, content) >= 0) {
      return checked.removeObject(content);
    } else {
      return checked != null ? checked.pushObject(content) : void 0;
    }
  }
});
